// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BookResponse struct {
	ID    int `json:"id"`
	Total int `json:"total"`
}

type NewBookRequest struct {
	Name  string `json:"name"`
	Total int    `json:"total"`
}
